title: David Garvey’s Weblog
author: David Garvey
description: Occasional thoughts.
url: https://davegarvey.github.io
baseurl: ""
lang: en-GB
timezone: Europe/Zurich

permalink: /:year/:month/:day/:title/
markdown: kramdown
excerpt_separator: "<!--more-->"

webmaster_verifications:
  google: wvyRR7rO0lJZubnRdZp2oWYLWyUvY0TNfCb6n1ikSMs

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

feed:
  path: feed.xml
  excerpt_only: true

exclude:
  - .github
  - Gemfile
  - Gemfile.lock
  - README.md
  - ideas.md
  - vendor
